apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-pact-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pactapp
  template:
    metadata:
      labels:
        app: pactapp
    spec:
      containers:
      - name: pactapp
        image: chinnudocker555/pactapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: pactapp-svc
spec:
  selector:
    app: pactapp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
